# Generated by Django 3.0.6 on 2020-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200521_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='project_image',
            field=models.ImageField(null=True, upload_to='projects/%Y/%m%d'),
        ),
    ]
